sudo: required
services:
  - docker

before_install:
  - docker build -t robertdominato/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true robertdominato/react-test npm test

after_success:
  - docker build -t robertdominato/multi-client ./client  
  - docker build -t robertdominato/multi-nginx ./nginx
  - docker build -t robertdominato/multi-server ./server
  - docker build -t robertdominato/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push robertdominato/multi-client
  - docker push robertdominato/multi-nginx
  - docker push robertdominato/multi-server
  - docker push robertdominato/multi-worker